In [6]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape
x.numel()

12

In [9]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.randn(3, 4)

tensor([[ 0.8849,  0.3821, -0.8004, -0.3770],
        [ 0.5665, -0.3341, -1.5028,  0.3496],
        [ 0.7497,  0.3442,  0.8248,  0.5197]])

In [11]:
torch.tensor([[0.0, 1.0], [2.0, 3.0]])

tensor([[0., 1.],
        [2., 3.]])

In [16]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.tensor([3, 4, 5, 9])
x, y, x + y, x - y, x * y, x / y


(tensor([1., 2., 3., 4.]),
 tensor([3, 4, 5, 9]),
 tensor([ 4.,  6.,  8., 13.]),
 tensor([-2., -2., -2., -5.]),
 tensor([ 3.,  8., 15., 36.]),
 tensor([0.3333, 0.5000, 0.6000, 0.4444]))

In [21]:
x = torch.randn(3, 4)
torch.exp(x)

tensor([[ 0.3968,  0.9797,  0.1704,  2.2754],
        [ 0.3766,  2.9776, 14.0861,  0.2894],
        [ 3.7763,  2.0532,  1.1560,  2.5959]])

In [22]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0], [8.0, 9.0, 10.0, 11.0]])
x, y, torch.cat([x, y], dim=0), torch.cat([x, y], dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [23]:
x == y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [24]:
x.sum()

tensor(66.)

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))